### ISSUE TITLE
error with buy function

### ISSUE THREAD

**Issue by orbittasd** [dQuadrant/cardano-marketplace#2]
Hi, I have been testing frontend and with two diferent accounts I put to sell a NFT, so when I try to Buy with the another account this happens
![image](https://user-images.githubusercontent.com/112282844/188324855-4064da0a-98ed-4cf8-bd64-df14193e4439.png)

ErrorKubærApi [Status 400] : TransactionValidityTranslationError (InlineDatumsNotSupported (TxOutFromInput (TxIn (TxId {_unTxId = SafeHash "7f14ebf610aed5b888f984e83d8dcc3618baac769beff390a38e4d6625324666"}) (TxIx 0))))

Do you know why this happens or how to fix that?
Thanks

**Comment by mesudip** [comment]
Thanks for reporting the issue. 
There was compatibility issue with Kuber in different era. Kuber in Babbage era treats datum parameter as inlineDatum, whereas hash of the datum was calculated in Alonzo era.

I've migrated the contract to V2 and added few other fixes required for migration in https://github.com/dQuadrant/cardano-marketplace/commit/9c0ff5efe306ff6b0332e06b33b46ef8f5351beb
